miniblog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
     path('about/',views.about,name='about'),
     path('contact/',views.contact,name='contact'),
     path('dashboard/',views.dashboard,name='dashboard'),
     path('signup/',views.user_signup,name='signup'),
     path('login/',views.user_login,name='login'),
     path('logout/',views.user_logout,name='logout'),
     path('addpost/',views.addpost,name='addpost'),
     path('changepass/',views.changepass,name='changepass'),
     path('updatepost/<int:id>/',views.updatepost,name='updatepost'),
     path('deletepost/<int:id>/',views.deletepost,name='deletepost'),
]

blog/models.py
"""
models.py
Defines database models for users and posts in the application.
"""

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    """Model representing a blog post."""

    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    desc = models.TextField()

blog/forms.py
"""
Forms module to handle user registration, login, and blog post forms.
"""

from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    UsernameField,
)
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput
from django.utils.translation import gettext_lazy as _

from .models import Post


class signupform(UserCreationForm):
    """Form for user registration using Django's UserCreationForm."""

    password1 = forms.CharField(
        label="Password", widget=PasswordInput(attrs={"class": "form-control"})
    )
    password2 = forms.CharField(
        label="Confirm Password", widget=PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]
        labels = {
            "first_name": "First Name",
            "last_name": "Last Name",
            "email": "Email",
        }
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
        }
        error_messages = {"username": {"required": "Enter your name"}}


class loginform(AuthenticationForm):
    """Form for user login extending Django's AuthenticationForm."""

    username = UsernameField(
        widget=forms.Textarea(attrs={"autofocus": True, "class": "form-control"})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "class": "form-control"}
        ),
    )


class PostForm(forms.ModelForm):
    """Form for creating and editing blog posts."""

    class Meta:
        model = Post
        fields = ["title", "desc"]
        labels = {"title": "Title", "desc": "Description"}
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "desc": forms.Textarea(attrs={"class": "form-control"}),
        }

blog/views.py
"""
views.py
Handles HTTP requests and routes for blog views and user authentication.
"""

from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect, HttpResponseRedirect
from .forms import loginform, signupform, PostForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from .models import Post
from django.contrib.auth.models import Group
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_GET, require_POST

from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

# Create your views here.
LOGIN_URL = "/login/"
DASHBOARD_URL = "/dashboard/"


@require_GET
def home(request):
    """View handling the home page."""
    posts = Post.objects.all()

    return render(request, "blog/home.html", {"posts": posts})


@require_GET
def about(request):
    return render(request, "blog/about.html")


@require_GET
def contact(request):
    return render(request, "blog/contact.html")


@login_required
@require_GET
def dashboard(request):
    """View handling the dashboard for authenticated users."""
    if request.user.is_authenticated:
        posts = Post.objects.all()
        return render(request, "blog/dashboard.html", {"posts": posts})
    else:
        return HttpResponseRedirect(LOGIN_URL)


@csrf_protect
@require_http_methods(["GET", "POST"])
def user_signup(request):
    if request.method == "POST":
        fm = signupform(request.POST)
        if fm.is_valid():
            xxx = fm.cleaned_data["username"]

            user = fm.save()
            messages.success(request, "Account was created for " + xxx)
            group = Group.objects.get(name="auther")
            user.groups.add(group)
            return HttpResponseRedirect(LOGIN_URL)
    else:
        fm = signupform()

    return render(request, "blog/signup.html", {"form": fm})


@csrf_protect
@require_http_methods(["GET", "POST"])
def user_login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            fm = loginform(request=request, data=request.POST)
            if fm.is_valid():
                uname = fm.cleaned_data["username"]
                upass = fm.cleaned_data["password"]
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request, user)
                    messages.success(request, "la moj gara")
                    return HttpResponseRedirect(DASHBOARD_URL)

        else:
            fm = loginform()

        return render(request, "blog/login.html", {"form": fm})
    else:
        return HttpResponseRedirect(DASHBOARD_URL)


@require_POST
def user_logout(request):
    logout(request)
    return HttpResponseRedirect("/")


@login_required
@csrf_protect
@require_http_methods(["GET", "POST"])
def addpost(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            fm = PostForm(request.POST)
            if fm.is_valid():
                title = fm.cleaned_data["title"]
                desc = fm.cleaned_data["desc"]
                pst = Post(title=title, desc=desc)
                pst.save()
                fm = PostForm()
        else:
            fm = PostForm()
        return render(request, "blog/post.html", {"form": fm})
    else:
        return HttpResponseRedirect(LOGIN_URL)


@login_required
@csrf_protect
@require_http_methods(["GET", "POST"])
def updatepost(request, id):
    if request.user.is_authenticated:
        if request.method == "POST":
            pi = Post.objects.get(pk=id)
            fm = PostForm(request.POST, instance=pi)
            if fm.is_valid():
                fm.save()
        else:
            pi = Post.objects.get(pk=id)
            fm = PostForm(instance=pi)

        return render(request, "blog/updatepost.html", {"form": fm})
    else:
        return HttpResponseRedirect(LOGIN_URL)


@login_required
@require_POST  # Only allow POST (no GET)
def deletepost(request, id):
    if request.user.is_authenticated:
        if request.method == "POST":
            pi = Post.objects.get(pk=id)
            pi.delete()

        return HttpResponseRedirect(DASHBOARD_URL)
    else:
        return HttpResponseRedirect(LOGIN_URL)


@login_required
@csrf_protect
@require_http_methods(["GET", "POST"])
def changepass(request):
    if request.method == "POST":
        fm = PasswordChangeForm(user=request.user, data=request.POST)
        if fm.is_valid():
            fm.save()
            update_session_auth_hash(request, fm.user)
            return HttpResponseRedirect(DASHBOARD_URL)

    else:
        fm = PasswordChangeForm(user=request.user)
    return render(request, "blog/changepass.html", {"fm": fm})

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
 <div class="col-sm-10">
 <h3 class="text-white my-5">about page</h3>

 <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas, saepe!</p>
 <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae labore unde error sit, dolore quibusdam praesentium officiis voluptatem distinctio, excepturi reiciendis! Possimus, praesentium doloremque laudantium ex et laboriosam quidem totam.</p>
 </div>
{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">
    <link rel="stylesheet" href=" {% static 'blog/css/style.css' %}">
    <title>Document</title>
</head>
<body >
<div class="container-fluid bg-dark">
 {% include 'blog/navbar.html' %}

</div>
 <div class ="container">
  <div class="row">
    <div class="col-sm-12"> 
       {% block msg %}
       {% endblock msg %}

    </div>
  </div>
  <div class="row">
   {% block side %}
   {% endblock side %}

   {% block content %}
   {% endblock content %}
  </div>
 </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
</body>
</html>

blog/templates/blog/changepass.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
 <div class="col-sm-10">
 <h3 class="text-white my-5">login page</h3>
 {% if messages %}
 {% for message in messages %}
 <p {% if message.tags %} class= 'alert alert-{{message.tags}} mb-5' {% endif %}>{{message}}</p>
 {% endfor %}
 {% endif %}
 
 <form action="" method="post" novalidate>
 {% csrf_token %}
{% for f in fm  %}
<div class ="form-group">
{{f.label}}{{f}}<small class = "text-warning">{{f.errors|striptags}}</small>
</div>
{% endfor %}
<input type="submit" value="login" class=" btn btn-primary">
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class ="alert alert-danger my-3">{{error}}</p>
{% endfor %}
{% endif %}

 </form>
 <a href="{% url 'dashboard' %}" class="btn btn-success">Cancle</a>
 
 
 </div>
{% endblock content %}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
  <h3 class="text-white my-5">Contact page</h3>
  <form>
    {% csrf_token %}
    <div class="row">
      <div class=" col-sm-4">
        <div class="form-group">
          <label for="inputName">Name</label>
          <input type="text" class="form-control" id="inputName" aria-describedby="namehelp" placeholder="Enter name">
          <small id="namehelp" class="form-text text-muted">We'll never share your name with anyone else.</small>
        </div>
      </div>
      <div class=" col-sm-8">
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
            placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
      </div>
    </div>

    <div class="form-group">

      <label for="message">Message</label>
      <textarea class="form-control" id="messgae" row="3"></textarea>
    </div>

    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>


</div>
{% endblock content %}

blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}
{% block msg %}

 {% if messages %}
 {% for message in messages %}
  <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" > {% endif %}
  <strong>{{message}}</strong> 
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
         <span aria-hidden="true">&times;</span>
         
     </button>
     
 </div>
 {% endfor %}
 {% endif %}
 {% endblock msg %}

 {% block content %}
 <div class="col-sm-10">
 <h2 class="text-white my-5">Dashboard page</h2>
 <a href="{% url 'addpost' %}" class="btn btn-success ">Add Post</a>
 <h4 class="text-center alert alert-info mt-3">Show my past data</h4>
 {% if posts %}
 <table class="table table-hover bg-white">
  <thead>
    <tr class="text-center">
      <th scope="col" style="width:2%">id</th>
      <th scope="col" style="width:28%">Title</th>
      <th scope="col" style="width:55%">Description</th>
      <th scope="col" style="width:15%">Action</th>
    </tr>
  </thead>
  <tbody>
  {% for post in posts  %}
    <tr>
      <th scope="row">{{post.id}}</th>
      <td>{{post.title}}</td>
      <td>{{post.desc}}</td>
      <td class="text-center">
      <a href="{% url 'updatepost' post.id %}" class="btn btn-warning btn-sm">Edit</a>
      {% if perms.blog.delete_post %}
      <form action="{% url 'deletepost' post.id %}" method="post" class="d-inline">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger btn-sm" value="Delete">
      {% endif %}
      </form>
      </td>
    </tr>
    {% endfor %}
   
  </tbody>
</table>
{% else %}
<h4 class="text-senter alert alert-warning">No record</h4>

{% endif %}
</div>
 
 {% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
 <div class="col-sm-10">
 <h3 class="text-white my-5">Home page</h3>
  {% for post in posts  %}
 <div class="jumbotron jumbotron-fluid jumbo-color">
  <div class="container">
    <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
    <p class="lead"> {{post.desc}}</p>
  </div>
</div>
{% endfor %}
 </div>
{% endblock content %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
 <div class="col-sm-10">
 <h3 class="text-white my-5">login page</h3>
 {% if messages %}
 {% for message in messages %}
 <p {% if message.tags %} class= 'alert alert-{{message.tags}} mb-5' {% endif %}>{{message}}</p>
 {% endfor %}
 {% endif %}
 
 <form action="" method="post" novalidate>
 {% csrf_token %}
{% for fm in form  %}
<div class ="form-group">
{{fm.label}}{{fm}}<small class = "text-warning">{{fm.errors|striptags}}</small>
</div>
{% endfor %}
<input type="submit" value="login" class=" btn btn-primary">
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class ="alert alert-danger my-3">{{error}}</p>
{% endfor %}
{% endif %}

 </form>
 
 
 </div>
{% endblock content %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">miniblog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" {% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" {% url 'contact' %}">Contact</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'changepass' %}">change Password</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'signup' %}">Sigup</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

blog/templates/blog/post.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class ="col-sm-10">
<h3 class="text-white my-5">Dashboard/ Add Post</h3>
<form action="" method="post" novalidate>
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="add" class="btn btn-success">
<a href="{% url 'dashboard' %}" class="btn btn-danger"> Cancel</a>
</form>

</div>



{% endblock content %}

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
 <div class="col-sm-10">
 <h3 class="text-white my-5">signup page</h3>
 
 <form action="" method="post" novalidate>
 {% csrf_token %}
{% for fm in form  %}
<div class ="form-group">
{{fm.label}}{{fm}}<small class = "text-warning">{{fm.errors|striptags}}</small>
</div>
{% endfor %}
<input type="submit" value="signup" class=" btn btn-primary">
{% if form.non_field_errors %} 
{% for error in form.non_field_errors %}
<p  class ="alert alert-danger my-3">{{error}}</p>

{% endfor %}     

{% endif %}

 </form>


 </div>
{% endblock content %}

blog/templates/blog/updatepost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class ="col-sm-10">
<h3 class="text-white my-5">Dashboard/ Update Post</h3>
<form action="" method="post" novalidate>
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Update" class="btn btn-success">
<a href="{% url 'dashboard' %}" class="btn btn-danger"> Cancel</a>
</form>

</div>


{% endblock content %}